"""init fait

Revision ID: 4f5f4e4eeea5
Revises: 
Create Date: 2020-02-07 15:41:38.721941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5f4e4eeea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_Acts',
    sa.Column('idAct', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('unitaryPrice', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idAct')
    )
    op.create_table('T_Users',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('connectionNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=True)
    op.create_index(op.f('ix_actions_symbol'), 'actions', ['symbol'], unique=True)
    op.create_table('T_Cpts',
    sa.Column('idCpt', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('cptDate', sa.DateTime(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['T_Users.idUser'], ),
    sa.PrimaryKeyConstraint('idCpt')
    )
    op.create_table('T_Ords',
    sa.Column('idOrd', sa.Integer(), nullable=False),
    sa.Column('sens', sa.Text(), nullable=True),
    sa.Column('ordDate', sa.DateTime(), nullable=False),
    sa.Column('PriceAchat', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('idAct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAct'], ['T_Acts.idAct'], ),
    sa.PrimaryKeyConstraint('idOrd')
    )
    op.create_table('ordres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=True),
    sa.Column('prix', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('T_OrdLines',
    sa.Column('idOrdLine', sa.Integer(), nullable=False),
    sa.Column('idAct', sa.Integer(), nullable=True),
    sa.Column('idCpt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAct'], ['T_Acts.idAct'], ),
    sa.ForeignKeyConstraint(['idCpt'], ['T_Cpts.idCpt'], ),
    sa.PrimaryKeyConstraint('idOrdLine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_OrdLines')
    op.drop_table('ordres')
    op.drop_table('T_Ords')
    op.drop_table('T_Cpts')
    op.drop_index(op.f('ix_actions_symbol'), table_name='actions')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    op.drop_table('T_Users')
    op.drop_table('T_Acts')
    # ### end Alembic commands ###
