"""rename tables Action, Ordre, Seuil

Revision ID: ec18ba94db18
Revises: 4b38a1238c58
Create Date: 2020-01-04 20:07:57.599603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec18ba94db18'
down_revision = '4b38a1238c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('symbole', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=True)
    op.create_index(op.f('ix_actions_symbole'), 'actions', ['symbole'], unique=True)
    op.create_table('ordres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=True),
    sa.Column('prix', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seuils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seuilMax', sa.Integer(), nullable=True),
    sa.Column('seuilMin', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ordre')
    op.drop_index('ix_action_name', table_name='action')
    op.drop_index('ix_action_symbole', table_name='action')
    op.drop_table('action')
    op.drop_table('seuil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seuil',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seuilMax', sa.INTEGER(), nullable=True),
    sa.Column('seuilMin', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('action_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('symbole', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_symbole', 'action', ['symbole'], unique=1)
    op.create_index('ix_action_name', 'action', ['name'], unique=1)
    op.create_table('ordre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.INTEGER(), nullable=True),
    sa.Column('prix', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('action_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seuils')
    op.drop_table('ordres')
    op.drop_index(op.f('ix_actions_symbole'), table_name='actions')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
